openapi: 3.0.0
info: 
  title: Service for products page
  version: 2.0.0

x-amazon-apigateway-request-validator: params-only

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: integer
    Error:
      type: string