service: authorization-service

frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

package:
  individually: true
  patterns:
    - "!**"
    - "./dist"

functions:
  basicAuthorizer:
    handler: dist/basicAuthorizer.basicAuthorizer
    package:
      patterns:
        - "!dist/**"
        - "dist/basicAuthorizer.js"

